// ---------------------------------------------------------------------------
// connectors/gemini/tools.js
//
// delegate_research (2026-07-27 rename + split, was Delegate_web_fetch): one
// tool, two mutually-exclusive modes, selected by which args are passed --
// PRECISION MODE (url + question): fetches a URL and hands the page content
// + question to Gemini in a single call, returning ONLY Gemini's answer --
// not the raw page. This is the original token-saving mechanism (see plan
// discussion, 2026-07-25): the existing web_fetch tool returns up to
// 500,000 raw characters into the calling model's context by default. This
// mode instead lets Gemini read the firehose server-side and returns a
// compact answer, at the cost of one extra API call + latency. Stays inline
// in this file (not research.js) since it's a genuinely simpler, one-shot
// code path with no loop.
// WIDE MODE (task): delegates to runResearch() in research.js -- as of
// 2026-07-27 a single, WEB-ONLY call to Exa's /answer endpoint (search +
// synthesis in one shot), not a multi-step Gemini loop -- see research.js's
// header for why that loop was retired and why this stays WEB-ONLY (kept
// separate from delegate_agent's GitHub/Notion/Cloudflare/Context7/Mem0
// access) regardless of provider.
//
// NOTE ON WHY PRECISION MODE SAVES TOKENS AND OTHER SIMILAR-LOOKING TOOLS
// DON'T: any argument a caller passes INTO a tool call (e.g. "summarize this
// text: ...") already had to be generated by the caller first, so passing
// raw content as a tool argument never saves anything. The savings here
// come entirely from fetching server-side -- the caller supplies only a URL
// and a question, never the page content itself.
//
// NOTION WRITE ISOLATION (2026-07-25 plan): this tool's optional Notion
// logging ALWAYS targets GEMINI_NOTION_ROOT_PAGE_ID -- that constant is not
// exposed as a tool parameter anywhere in this file, so there is no
// argument-based path for a Gemini-driven write to land anywhere else in
// the workspace (Memory Index, Entity Index, Job Leads, etc.), which the
// Claude-side dedup/sync tools depend on staying uncontaminated. Reads are
// unrestricted -- future Gemini tools that need Notion context can query
// any page/database via the existing connectors/notion/client.js exports.
// ---------------------------------------------------------------------------

import { z } from "zod";
import { geminiGenerate } from "./client.js";
import { runInvestigation } from "./delegate.js";
import { runResearch } from "../exa/research.js";
import { fetchUrl, htmlToText } from "../fetch/client.js";
import { doCreatePage } from "../notion/tools.js";
import { GEMINI_NOTION_ROOT_PAGE_ID } from "../../config.js";

const DEFAULT_MAX_SOURCE_CHARS = 300000;

export function register(server) {

  server.tool(
    "delegate_research",
    "DOES: Web research, ONE of two mutually-exclusive modes selected by which args you pass.\n" +
    "MODE url+question (PRECISION, via Gemini): fetches the URL, hands page + question to Gemini, returns ONLY Gemini's compact answer -- not the raw page. Use for a specific answer from a page (e.g. 'does this doc mention rate limits?').\n" +
    "NOT: exact wording, code snippets to copy, or content to edit -> use web_fetch instead.\n" +
    "MODE task (WIDE, via Exa): single-shot Exa /answer call (search+synthesis in one), returns answer+sources. Use for 'current status of X' or comparing multiple sources. WEB-ONLY -- no GitHub/Notion/Cloudflare -> use delegate_agent for internal-systems investigations instead.\n" +
    "RULE: pass EITHER url+question OR task -- never both, never neither.\n" +
    "RULE (wide mode): single-shot only -- max_steps/resume_run_id accepted for param compatibility with delegate_agent but have no real effect.",
    {
      url:              z.string().url().optional().describe("PRECISION MODE: the URL to fetch. Must be paired with `question`; do not combine with `task`."),
      question:         z.string().optional().describe("PRECISION MODE: the specific question to answer using the page's content. Be specific -- vague questions get vague answers. Must be paired with `url`."),
      max_source_chars: z.number().optional().describe(`PRECISION MODE only: truncate the fetched page to this many characters before sending to Gemini (default: ${DEFAULT_MAX_SOURCE_CHARS}).`),
      task:             z.string().optional().describe("WIDE MODE: the research task/question, described with enough context for a single Exa /answer call to act on without needing to ask you anything back -- it can't. Do not combine with `url`/`question`."),
      max_steps:        z.number().optional().describe("WIDE MODE only: accepted for parameter compatibility with delegate_agent, but has no effect -- wide mode is always a single Exa /answer call regardless of this value."),
      resume_run_id:    z.string().optional().describe("WIDE MODE only: accepted for parameter compatibility with delegate_agent, but wide mode is a single-shot Exa call with no checkpoint -- passing this returns a result explaining there's nothing to resume, rather than continuing a prior run."),
      show_transcript:  z.boolean().optional().describe("WIDE MODE only: include the full step-by-step tool-call transcript in the response, even on a successful run (default: false)."),
      log_to_notion:    z.boolean().optional().describe("Whether to log this call's inputs/outputs as a page under the Gemini section of Notion (default: false). The write always targets the fixed Gemini root page -- this cannot be redirected elsewhere."),
    },
    async ({ url, question, max_source_chars = DEFAULT_MAX_SOURCE_CHARS, task, max_steps = 20, resume_run_id, show_transcript = false, log_to_notion = false }) => {
      // Mode selection is by presence of args, not an explicit "mode" param --
      // see file header. Validate mutual exclusivity up front so a caller who
      // passes both (or neither) gets a clear error instead of one set of
      // args being silently ignored.
      const hasPrecisionArgs = url !== undefined || question !== undefined;
      const hasWideArgs = task !== undefined || resume_run_id !== undefined;

      if (hasPrecisionArgs && hasWideArgs) {
        return { content: [{ type: "text", text: "Invalid arguments: pass EITHER url+question (precision mode) OR task/resume_run_id (wide mode), not both." }], isError: true };
      }
      if (!hasPrecisionArgs && !hasWideArgs) {
        return { content: [{ type: "text", text: "Missing arguments: pass either url+question (precision mode) or task (wide mode)." }], isError: true };
      }
      if (hasPrecisionArgs && (url === undefined || question === undefined)) {
        return { content: [{ type: "text", text: "Precision mode requires BOTH url and question." }], isError: true };
      }
      if (hasWideArgs && !task && !resume_run_id) {
        return { content: [{ type: "text", text: "Wide mode requires task, unless resuming a live checkpoint via resume_run_id." }], isError: true };
      }
      // Same off-by-invalid-input guard as delegate_agent's max_steps check --
      // see tools.js's delegate_agent handler comment for the full reasoning.
      if (hasWideArgs && max_steps !== undefined && (!Number.isInteger(max_steps) || max_steps < 1)) {
        return { content: [{ type: "text", text: `Invalid max_steps: ${max_steps}. Must be a positive integer (at least 1); the hard cap is 30 regardless of a larger value.` }], isError: true };
      }

      if (hasPrecisionArgs) {
        // ---- Precision mode: single fetch + single geminiGenerate call ----
        let fetched;
        try {
          fetched = await fetchUrl(url);
        } catch (err) {
          return { content: [{ type: "text", text: `Fetch failed: ${err?.message ?? String(err)}` }], isError: true };
        }

        let sourceText = fetched.contentType.includes("text/html") ? htmlToText(fetched.text) : fetched.text;
        const truncated = sourceText.length > max_source_chars;
        if (truncated) sourceText = sourceText.slice(0, max_source_chars);

        const prompt =
          `Answer the question below using ONLY the page content provided. ` +
          `Be concise and specific. If the answer isn't in the content, say so plainly rather than guessing.\n\n` +
          `Question: ${question}\n\n` +
          `Page content (from ${url}${truncated ? ", truncated" : ""}):\n${sourceText}`;

        let answer;
        try {
          answer = await geminiGenerate(prompt);
        } catch (err) {
          return { content: [{ type: "text", text: `Gemini call failed: ${err?.message ?? String(err)}` }], isError: true };
        }

        let notionNote = "";
        if (log_to_notion) {
          try {
            const logged = await doCreatePage({
              parent_id:   GEMINI_NOTION_ROOT_PAGE_ID,
              parent_type: "page",
              title:       `delegate_research (precision): ${url}`,
              content:     `URL: ${url}\nQuestion: ${question}\n\nAnswer:\n${answer}`,
              one_off:     true,
            });
            notionNote = `\n\n(Logged to Notion: ${logged.url})`;
          } catch (err) {
            // Best-effort -- a failed log write shouldn't hide the answer the
            // caller actually asked for.
            notionNote = `\n\n(⚠️ Notion logging failed: ${err.message})`;
          }
        }

        return { content: [{ type: "text", text: `${answer}${notionNote}` }] };
      }

      // ---- Wide mode: multi-step, web-only research loop (research.js) ----
      let result;
      try {
        result = await runResearch({ task, max_steps, resume_run_id });
      } catch (err) {
        return { content: [{ type: "text", text: `Research failed: ${err?.message ?? String(err)}` }], isError: true };
      }

      // On a resumed run, task may be undefined here -- runResearch returns
      // the effective task text it actually used, mirroring delegate_agent's
      // handling below.
      const effectiveTask = task || result.task || "(resumed run)";

      let notionNote = "";
      if (log_to_notion) {
        try {
          const logged = await doCreatePage({
            parent_id:   GEMINI_NOTION_ROOT_PAGE_ID,
            parent_type: "page",
            title:       `${result.failed ? "delegate_research (partial): " : "delegate_research: "}${effectiveTask.slice(0, 80)}`,
            content:     `Task: ${effectiveTask}\n\nrunId: ${result.runId}${result.failed ? " (resumable)" : ""}\n\nSteps taken: ${result.steps}\n\nTool calls:\n${result.transcript.join("\n") || "(none)"}\n\nAnswer:\n${result.answer}`,
            one_off:     true,
          });
          notionNote = `\n\n(Logged to Notion: ${logged.url})`;
        } catch (err) {
          notionNote = `\n\n(⚠️ Notion logging failed: ${err.message})`;
        }
      }

      const transcriptBlock = result.transcript?.length && (result.failed || show_transcript)
        ? `\n\n${result.failed ? "Tool calls completed before the failure" : "Tool call transcript"}:\n${result.transcript.join("\n")}`
        : "";

      return { content: [{ type: "text", text: `${result.answer}${transcriptBlock}\n\n(${result.steps} step(s) taken)${notionNote}` }], isError: !!result.failed };
    }
  );

  server.tool(
    "delegate_agent",
    "DOES: Open-ended, multi-step READ-ONLY investigation across GitHub/Notion/Cloudflare -- Gemini runs its own server-side loop (bounded by max_steps) reading files/trees/commits/logs/pages across as many turns as needed, cross-checks claims BETWEEN sources, flags discrepancies, returns one synthesized answer.\n" +
    "RULE: default choice for multi-file or open-ended investigation -- prefer over manual read_file/get_file_tree/list_directory loops UNLESS you need exactly one named file.\n" +
    "NOT: web access -> use delegate_research (task param, wide mode) instead. NOT: any write -> read-only by design.\n" +
    "USE FOR: e.g. 'why is CI failing on PR #42', 'summarize what changed in this repo over the last week' -- cases needing 5-10+ manual cross-system calls otherwise.\n" +
    "RESUME: failed/partial run -> response includes resume_run_id -> pass back to continue from last completed step instead of restarting.",
    {
      task:          z.string().optional().describe("The investigation task/question, described with enough context (repo names, time ranges, etc.) for Gemini to act without needing to ask you anything back -- it can't. Ignored when resume_run_id resolves to a live checkpoint (the original task from that run is reused). Optional ONLY when resume_run_id is given and its checkpoint is still live; required otherwise -- omitting it on a fresh run (no resume_run_id, or an expired one) returns an error rather than silently proceeding with no task."),
      max_steps:     z.number().optional().describe("Max tool-use turns Gemini gets before being forced to answer (default 20, hard cap 30 regardless of this value). On a resumed run this is the new ceiling, not additional steps on top of what's already done."),
      log_to_notion: z.boolean().optional().describe("Whether to log the task, step-by-step tool calls, and final answer as a page under the Gemini section of Notion (default: false). Write always targets the fixed Gemini root page."),
      resume_run_id: z.string().optional().describe("A runId returned from a previous failed/partial delegate_agent call. If its checkpoint is still live (1 hour TTL), continues that run's conversation instead of starting fresh."),
      show_transcript: z.boolean().optional().describe("Include the full step-by-step tool-call transcript in the response, even on a successful run (default: false). Useful for debugging what Gemini actually called and in what order/grouping -- e.g. checking whether independent calls were batched into the same step. On a failed/partial run the transcript is always shown regardless of this flag."),
    },
    async ({ task, max_steps = 20, log_to_notion = false, resume_run_id, show_transcript = false }) => {
      // task is only genuinely optional when resuming a live checkpoint --
      // runInvestigation ignores task entirely in that branch (it rebuilds
      // `contents` straight from the saved checkpoint). On a fresh run (no
      // resume_run_id, or one whose checkpoint already expired), there is no
      // saved task to fall back on, so fail loudly here rather than letting
      // runInvestigation start a conversation with an undefined task.
      if (!task && !resume_run_id) {
        return {
          content: [{ type: "text", text: "Missing required argument: task must be provided unless resuming a live checkpoint via resume_run_id." }],
          isError: true,
        };
      }

      // max_steps has no floor in its Zod type (z.number().optional() accepts
      // 0, negatives, and non-integers), but runInvestigation's loop is a
      // `for (step = startStep; step <= cappedSteps; ...)` that simply never
      // executes when cappedSteps < startStep -- silently "succeeding" with
      // zero Gemini calls made and a confusing "reached the step cap of 0"
      // answer instead of surfacing that the input itself was invalid.
      if (max_steps !== undefined && (!Number.isInteger(max_steps) || max_steps < 1)) {
        return {
          content: [{ type: "text", text: `Invalid max_steps: ${max_steps}. Must be a positive integer (at least 1); the hard cap is 30 regardless of a larger value.` }],
          isError: true,
        };
      }

      let result;
      try {
        result = await runInvestigation({ task, max_steps, resume_run_id });
      } catch (err) {
        return { content: [{ type: "text", text: `Investigation failed: ${err?.message ?? String(err)}` }], isError: true };
      }

      // On a resumed run, `task` may be undefined here (a fresh run always has
      // it, per the guard above) -- runInvestigation returns the effective
      // task text it actually used (the caller-supplied one, or the one
      // restored from the checkpoint) so logging/titling never has to guess.
      const effectiveTask = task || result.task || "(resumed run)";

      let notionNote = "";
      if (log_to_notion) {
        try {
          const logged = await doCreatePage({
            parent_id:   GEMINI_NOTION_ROOT_PAGE_ID,
            parent_type: "page",
            title:       `${result.failed ? "investigate (partial): " : "investigate: "}${effectiveTask.slice(0, 80)}`,
            content:     `Task: ${effectiveTask}\n\nrunId: ${result.runId}${result.failed ? " (resumable)" : ""}\n\nSteps taken: ${result.steps}\n\nTool calls:\n${result.transcript.join("\n") || "(none)"}\n\nAnswer:\n${result.answer}`,
            one_off:     true,
          });
          notionNote = `\n\n(Logged to Notion: ${logged.url})`;
        } catch (err) {
          notionNote = `\n\n(\u26a0\ufe0f Notion logging failed: ${err.message})`;
        }
      }

      // On a failed/partial run, the tool calls already completed are real
      // work (and already checkpointed to Redis -- see runInvestigation's
      // comment) that shouldn't be thrown away. Print them here instead of
      // just a step count, so the caller can see what was actually found
      // before the failure without needing a resume_run_id round-trip or
      // log_to_notion just to inspect them.
      const transcriptBlock = result.transcript?.length && (result.failed || show_transcript)
        ? `\n\n${result.failed ? "Tool calls completed before the failure" : "Tool call transcript"}:\n${result.transcript.join("\n")}`
        : "";

      return { content: [{ type: "text", text: `${result.answer}${transcriptBlock}\n\n(${result.steps} step(s) taken)${notionNote}` }], isError: !!result.failed };
    }
  );
}
