// ---------------------------------------------------------------------------
// connectors/gemini/tools.js
//
// web_fetch_and_ask: fetches a URL and a question server-side, hands the
// page content + question to Gemini, and returns ONLY Gemini's answer --
// not the raw page. This is the actual token-saving mechanism (see plan
// discussion, 2026-07-25): the existing web_fetch tool returns up to
// 500,000 raw characters into the calling model's context by default. This
// tool instead lets Gemini read the firehose server-side and returns a
// compact answer, at the cost of one extra API call + latency.
//
// NOTE ON WHY THIS SAVES TOKENS AND OTHER SIMILAR-LOOKING TOOLS DON'T: any
// argument a caller passes INTO a tool call (e.g. "summarize this text: ...")
// already had to be generated by the caller first, so passing raw content
// as a tool argument never saves anything. The savings here come entirely
// from fetching server-side -- the caller supplies only a URL and a
// question, never the page content itself.
//
// NOTION WRITE ISOLATION (2026-07-25 plan): this tool's optional Notion
// logging ALWAYS targets GEMINI_NOTION_ROOT_PAGE_ID -- that constant is not
// exposed as a tool parameter anywhere in this file, so there is no
// argument-based path for a Gemini-driven write to land anywhere else in
// the workspace (Memory Index, Entity Index, Job Leads, etc.), which the
// Claude-side dedup/sync tools depend on staying uncontaminated. Reads are
// unrestricted -- future Gemini tools that need Notion context can query
// any page/database via the existing connectors/notion/client.js exports.
// ---------------------------------------------------------------------------

import { z } from "zod";
import { geminiGenerate } from "./client.js";
import { runInvestigation } from "./delegate.js";
import { fetchUrl, htmlToText } from "../fetch/client.js";
import { doCreatePage } from "../notion/tools.js";
import { GEMINI_NOTION_ROOT_PAGE_ID } from "../../config.js";

const DEFAULT_MAX_SOURCE_CHARS = 300000;

export function register(server) {

  server.tool(
    "web_fetch_and_ask",
    "Fetch a URL and answer a specific question about its content, WITHOUT returning the raw page. Fetching and reading happen server-side via Gemini -- only Gemini's compact answer is returned to you. Use this instead of web_fetch whenever you need a specific answer from a page rather than the page's exact text (e.g. \"does this doc mention rate limits?\" rather than \"give me this page verbatim\"). Not a substitute for web_fetch when you need exact wording, code snippets to copy, or content to edit.",
    {
      url:              z.string().url().describe("The URL to fetch"),
      question:         z.string().describe("The specific question to answer using the page's content. Be specific -- vague questions get vague answers."),
      max_source_chars: z.number().optional().describe(`Truncate the fetched page to this many characters before sending to Gemini (default: ${DEFAULT_MAX_SOURCE_CHARS})`),
      log_to_notion:    z.boolean().optional().describe("Whether to log this URL/question/answer as a page under the Gemini section of Notion (default: true). The write always targets the fixed Gemini root page -- this cannot be redirected elsewhere."),
    },
    async ({ url, question, max_source_chars = DEFAULT_MAX_SOURCE_CHARS, log_to_notion = true }) => {
      let fetched;
      try {
        fetched = await fetchUrl(url);
      } catch (err) {
        return { content: [{ type: "text", text: `Fetch failed: ${err.message}` }], isError: true };
      }

      let sourceText = fetched.contentType.includes("text/html") ? htmlToText(fetched.text) : fetched.text;
      const truncated = sourceText.length > max_source_chars;
      if (truncated) sourceText = sourceText.slice(0, max_source_chars);

      const prompt =
        `Answer the question below using ONLY the page content provided. ` +
        `Be concise and specific. If the answer isn't in the content, say so plainly rather than guessing.\n\n` +
        `Question: ${question}\n\n` +
        `Page content (from ${url}${truncated ? ", truncated" : ""}):\n${sourceText}`;

      let answer;
      try {
        answer = await geminiGenerate(prompt);
      } catch (err) {
        return { content: [{ type: "text", text: `Gemini call failed: ${err.message}` }], isError: true };
      }

      let notionNote = "";
      if (log_to_notion) {
        try {
          const logged = await doCreatePage({
            parent_id:   GEMINI_NOTION_ROOT_PAGE_ID,
            parent_type: "page",
            title:       `web_fetch_and_ask: ${url}`,
            content:     `URL: ${url}\nQuestion: ${question}\n\nAnswer:\n${answer}`,
            one_off:     true,
          });
          notionNote = `\n\n(Logged to Notion: ${logged.url})`;
        } catch (err) {
          // Best-effort -- a failed log write shouldn't hide the answer the
          // caller actually asked for.
          notionNote = `\n\n(⚠️ Notion logging failed: ${err.message})`;
        }
      }

      return { content: [{ type: "text", text: `${answer}${notionNote}` }] };
    }
  );

  server.tool(
    "gemini_investigate",
    "Delegate an open-ended, multi-step READ-ONLY investigation to Gemini instead of doing it yourself one tool call at a time. Gemini runs its own loop server-side -- reading GitHub files/trees/commits, Cloudflare Workers logs, and Notion pages/databases across as many turns as it needs (bounded by max_steps) -- and returns one synthesized answer. Use this for things like \"why is CI failing on PR #42\" or \"summarize what changed in this repo over the last week\" where you'd otherwise need 5-10 separate manual tool calls. Not for anything requiring a write -- this tool is read-only by design.",
    {
      task:          z.string().describe("The investigation task/question, described with enough context (repo names, time ranges, etc.) for Gemini to act without needing to ask you anything back -- it can't."),
      max_steps:     z.number().optional().describe("Max tool-use turns Gemini gets before being forced to answer (default 6, hard cap 20 regardless of this value)."),
      log_to_notion: z.boolean().optional().describe("Whether to log the task, step-by-step tool calls, and final answer as a page under the Gemini section of Notion (default: true). Write always targets the fixed Gemini root page."),
    },
    async ({ task, max_steps = 6, log_to_notion = true }) => {
      let result;
      try {
        result = await runInvestigation({ task, max_steps });
      } catch (err) {
        return { content: [{ type: "text", text: `Investigation failed: ${err.message}` }], isError: true };
      }

      let notionNote = "";
      if (log_to_notion) {
        try {
          const logged = await doCreatePage({
            parent_id:   GEMINI_NOTION_ROOT_PAGE_ID,
            parent_type: "page",
            title:       `investigate: ${task.slice(0, 80)}`,
            content:     `Task: ${task}\n\nSteps taken: ${result.steps}\n\nTool calls:\n${result.transcript.join("\n") || "(none)"}\n\nAnswer:\n${result.answer}`,
            one_off:     true,
          });
          notionNote = `\n\n(Logged to Notion: ${logged.url})`;
        } catch (err) {
          notionNote = `\n\n(\u26a0\ufe0f Notion logging failed: ${err.message})`;
        }
      }

      return { content: [{ type: "text", text: `${result.answer}\n\n(${result.steps} step(s) taken)${notionNote}` }] };
    }
  );
}
